/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/github/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["callback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/github/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["start"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/github-app/authorize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["github_app_authorize"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/github-app/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["github_app_callback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repositories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_repositories"];
    put?: never;
    post: operations["create_repository"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repositories/{owner}/{name}/pull-requests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_pull_requests"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repositories/{owner}/{name}/pull-requests/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sync_pull_requests"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repositories/{owner}/{name}/pull-requests/{number}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_pull_request_detail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repositories/{owner}/{name}/pull-requests/{number}/diff": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_pull_request_diff"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repositories/{owner}/{name}/pull-requests/{number}/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sync_pull_request_detail"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repositories/{owner}/{name}/pull-requests/{number}/timeline/older": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["load_older_pull_request_timeline"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_settings"];
    put: operations["put_settings"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateRepositoryRequest: {
      repository: string;
    };
    CreateRepositoryResponse: {
      repository: components["schemas"]["RepositoryDto"];
    };
    HealthResponse: {
      database: components["schemas"]["HealthStatus"];
      status: components["schemas"]["HealthStatus"];
    };
    /** @enum {string} */
    HealthStatus: "ok";
    ListPullRequestsResponse: {
      pullRequests: components["schemas"]["PullRequestDto"][];
    };
    ListRepositoriesResponse: {
      repositories: components["schemas"]["RepositoryDto"][];
    };
    MeResponse: {
      user?: null | components["schemas"]["UserDto"];
    };
    PullRequestCheckRunDto: {
      name: string;
      state: string;
      summary?: string | null;
      title?: string | null;
      url?: string | null;
    };
    PullRequestCommentDto: {
      authorLogin?: string | null;
      body?: string | null;
    };
    PullRequestCommitDto: {
      message: string;
      sha: string;
    };
    PullRequestDetailDto: {
      body?: string | null;
      checkRuns: components["schemas"]["PullRequestCheckRunDto"][];
      commits: components["schemas"]["PullRequestCommitDto"][];
      files: components["schemas"]["PullRequestFileDto"][];
      issueComments: components["schemas"]["PullRequestCommentDto"][];
      reviewComments: components["schemas"]["PullRequestCommentDto"][];
      reviewDecision?: string | null;
      reviews: components["schemas"]["PullRequestReviewDto"][];
      statuses: components["schemas"]["PullRequestStatusDto"][];
      syncedAt: string;
      timeline: components["schemas"]["PullRequestTimelineEventDto"][];
      timelinePagination: components["schemas"]["PullRequestTimelinePaginationDto"];
    };
    PullRequestDetailResponse: {
      pullRequestDetail: components["schemas"]["PullRequestDetailDto"];
    };
    PullRequestDiffContentDto:
      | {
          /** @enum {string} */
          kind: "binary";
        }
      | {
          hunks: components["schemas"]["PullRequestDiffHunkDto"][];
          /** @enum {string} */
          kind: "text";
        };
    PullRequestDiffFileDto: {
      /** Format: int64 */
      additions: number;
      content: components["schemas"]["PullRequestDiffContentDto"];
      /** Format: int64 */
      deletions: number;
      operation: components["schemas"]["PullRequestDiffFileOperationDto"];
    };
    /** @enum {string} */
    PullRequestDiffFileModeDto: "100644" | "100755" | "120000" | "160000";
    PullRequestDiffFileOperationDto:
      | {
          /** @enum {string} */
          kind: "added";
          mode: components["schemas"]["PullRequestDiffFileModeDto"];
          path: string;
        }
      | {
          /** @enum {string} */
          kind: "deleted";
          mode: components["schemas"]["PullRequestDiffFileModeDto"];
          path: string;
        }
      | {
          /** @enum {string} */
          kind: "modified";
          modeChange: components["schemas"]["PullRequestDiffModeChangeDto"];
          path: string;
        }
      | {
          /** @enum {string} */
          kind: "renamed";
          modeChange: components["schemas"]["PullRequestDiffModeChangeDto"];
          newPath: string;
          oldPath: string;
        }
      | {
          /** @enum {string} */
          kind: "copied";
          modeChange: components["schemas"]["PullRequestDiffModeChangeDto"];
          newPath: string;
          oldPath: string;
        };
    PullRequestDiffHunkDto: {
      context: string | null;
      lines: components["schemas"]["PullRequestDiffLineDto"][];
      /** Format: int64 */
      newCount: number;
      /** Format: int64 */
      newStart: number;
      /** Format: int64 */
      oldCount: number;
      /** Format: int64 */
      oldStart: number;
    };
    PullRequestDiffLineDto:
      | {
          content: string;
          /** @enum {string} */
          kind: "context";
          missingNewline: boolean;
          /** Format: int64 */
          newLine: number;
          /** Format: int64 */
          oldLine: number;
        }
      | {
          content: string;
          /** @enum {string} */
          kind: "addition";
          missingNewline: boolean;
          /** Format: int64 */
          newLine: number;
        }
      | {
          content: string;
          /** @enum {string} */
          kind: "deletion";
          missingNewline: boolean;
          /** Format: int64 */
          oldLine: number;
        };
    PullRequestDiffModeChangeDto:
      | {
          /** @enum {string} */
          kind: "unchanged";
        }
      | {
          /** @enum {string} */
          kind: "changed";
          newMode: components["schemas"]["PullRequestDiffFileModeDto"];
          oldMode: components["schemas"]["PullRequestDiffFileModeDto"];
        };
    PullRequestDiffResponse: {
      files: components["schemas"]["PullRequestDiffFileDto"][];
      syncedAt: string;
    };
    PullRequestDto: {
      authorLogin?: string | null;
      closedAt?: string | null;
      createdAt: string;
      draft: boolean;
      /** Format: int64 */
      githubId: number;
      htmlUrl: string;
      mergedAt?: string | null;
      /** Format: int64 */
      number: number;
      state: string;
      syncedAt: string;
      title: string;
      updatedAt: string;
    };
    /** @enum {string} */
    PullRequestErrorCode:
      | "authenticationRequired"
      | "authorizationRequired"
      | "diffParseFailed"
      | "diffResourceLimitExceeded"
      | "diffUnavailable"
      | "invalidPullRequest"
      | "invalidRepository"
      | "pullRequestNotFound"
      | "repositoryNotTracked"
      | "syncFailed";
    PullRequestErrorResponse: {
      error: components["schemas"]["PullRequestErrorCode"];
    };
    PullRequestFileDto: {
      filename: string;
      status: string;
    };
    PullRequestReviewDto: {
      authorLogin?: string | null;
      state: string;
    };
    PullRequestStatusDto: {
      context: string;
      description?: string | null;
      state: string;
      url?: string | null;
    };
    PullRequestSyncPaginationDto:
      | {
          /** @enum {string} */
          kind: "complete";
        }
      | {
          /** @enum {string} */
          kind: "hasMore";
          /** Format: int64 */
          nextPage: number;
        };
    PullRequestTimelineEventDto: {
      actorLogin?: string | null;
      event: components["schemas"]["PullRequestTimelineEventKindDto"];
      id?: string | null;
      occurredAt?: string | null;
    };
    PullRequestTimelineEventKindDto:
      | {
          body?: string | null;
          /** @enum {string} */
          kind: "commented";
          url?: string | null;
        }
      | {
          commitSha?: string | null;
          /** @enum {string} */
          kind: "committed";
          message?: string | null;
          title?: string | null;
          url?: string | null;
        }
      | {
          body?: string | null;
          /** @enum {string} */
          kind: "reviewed";
          reviewComments: components["schemas"]["PullRequestTimelineReviewCommentsDto"];
          state?: string | null;
          url?: string | null;
        }
      | {
          /** @enum {string} */
          kind: "closed";
        }
      | {
          /** @enum {string} */
          kind: "reopened";
        }
      | {
          commitSha?: string | null;
          /** @enum {string} */
          kind: "merged";
        }
      | {
          /** @enum {string} */
          kind: "readyForReview";
        }
      | {
          /** @enum {string} */
          kind: "convertedToDraft";
        }
      | {
          /** @enum {string} */
          kind: "reviewRequested";
          reviewer?: string | null;
        }
      | {
          /** @enum {string} */
          kind: "reviewRequestRemoved";
          reviewer?: string | null;
        }
      | {
          body?: string | null;
          /** @enum {string} */
          kind: "reviewDismissed";
          state?: string | null;
          url?: string | null;
        }
      | {
          commitSha?: string | null;
          /** @enum {string} */
          kind: "headRefForcePushed";
        }
      | {
          commitSha?: string | null;
          /** @enum {string} */
          kind: "baseRefForcePushed";
        }
      | {
          /** @enum {string} */
          kind: "headRefDeleted";
          name?: string | null;
        }
      | {
          /** @enum {string} */
          kind: "headRefRestored";
        }
      | {
          /** @enum {string} */
          kind: "unknown";
          name?: string | null;
        };
    PullRequestTimelinePaginationDto:
      | {
          /** @enum {string} */
          kind: "complete";
        }
      | {
          /** @enum {string} */
          kind: "hasOlder";
        };
    PullRequestTimelineReviewCommentDto: {
      actorLogin?: string | null;
      body?: string | null;
      id?: string | null;
      occurredAt?: string | null;
      url?: string | null;
    };
    PullRequestTimelineReviewCommentsDto:
      | {
          items: components["schemas"]["PullRequestTimelineReviewCommentDto"][];
          /** @enum {string} */
          kind: "complete";
        }
      | {
          items: components["schemas"]["PullRequestTimelineReviewCommentDto"][];
          /** @enum {string} */
          kind: "truncated";
        };
    RepositoryDto: {
      createdAt: string;
      fullName: string;
      htmlUrl: string;
      name: string;
      owner: string;
      pullRequestsSyncError?: string | null;
      pullRequestsSyncedAt?: string | null;
    };
    /** @enum {string} */
    RepositoryErrorCode: "duplicateRepository" | "invalidRepository" | "repositorySaveFailed";
    RepositoryErrorResponse: {
      error: components["schemas"]["RepositoryErrorCode"];
    };
    SettingsResponse: {
      theme: components["schemas"]["Theme"];
    };
    SyncPullRequestResponse: {
      pullRequest: components["schemas"]["PullRequestDto"];
      pullRequestDetail: components["schemas"]["PullRequestDetailDto"];
    };
    SyncPullRequestsResponse: {
      pagination: components["schemas"]["PullRequestSyncPaginationDto"];
      pullRequests: components["schemas"]["PullRequestDto"][];
      syncedCount: number;
    };
    /** @enum {string} */
    Theme: "dark" | "light" | "system";
    UpdateSettingsRequest: {
      theme: components["schemas"]["Theme"];
    };
    UserDto: {
      avatarUrl?: string | null;
      displayName: string;
      id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  callback: {
    parameters: {
      query?: {
        code?: string | null;
        state?: string | null;
        error?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Creates a local session and redirects to the frontend */
      303: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description GitHub OAuth is not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  start: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirects to GitHub OAuth */
      303: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description GitHub OAuth is not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session cleared */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current authenticated user, if any */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
    };
  };
  github_app_authorize: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirects to GitHub App installation flow */
      303: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description GitHub App is not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  github_app_callback: {
    parameters: {
      query?: {
        installation_id?: number | null;
        setup_action?: string | null;
        state?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Stores GitHub App installation and redirects to frontend */
      303: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Backend health check */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  list_repositories: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user's tracked repositories */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListRepositoriesResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_repository: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRepositoryRequest"];
      };
    };
    responses: {
      /** @description Tracked repository created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateRepositoryResponse"];
        };
      };
      /** @description Invalid GitHub repository */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepositoryErrorResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepositoryErrorResponse"];
        };
      };
      /** @description Repository is already tracked */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepositoryErrorResponse"];
        };
      };
    };
  };
  list_pull_requests: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Stored pull requests for a tracked repository */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListPullRequestsResponse"];
        };
      };
      /** @description Invalid repository */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Repository is not tracked */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
    };
  };
  sync_pull_requests: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description One page of pull requests synced */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SyncPullRequestsResponse"];
        };
      };
      /** @description Invalid repository */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description GitHub App authorization required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description Repository is not tracked */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
    };
  };
  get_pull_request_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        name: string;
        number: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Stored pull request detail snapshot */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestDetailResponse"];
        };
      };
      /** @description Invalid repository or pull request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Repository or pull request detail is not stored */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
    };
  };
  get_pull_request_diff: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        name: string;
        number: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Parsed pull request diff */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestDiffResponse"];
        };
      };
      /** @description Invalid repository or pull request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description Repository or pull request detail is not stored */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description Stored pull request diff is unavailable */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description Stored pull request diff exceeds parser limits */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description Stored pull request diff could not be loaded or processed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
    };
  };
  sync_pull_request_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        name: string;
        number: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Pull request synced */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SyncPullRequestResponse"];
        };
      };
      /** @description Invalid repository or pull request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description GitHub App authorization required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description Repository is not tracked */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
    };
  };
  load_older_pull_request_timeline: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        name: string;
        number: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Stored pull request detail with the next older timeline page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestDetailResponse"];
        };
      };
      /** @description Invalid repository or pull request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description GitHub App authorization required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description Repository or pull request detail is not stored */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description GitHub timeline sync failed */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
    };
  };
  get_settings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user settings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  put_settings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateSettingsRequest"];
      };
    };
    responses: {
      /** @description Updated user settings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
