/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/github/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["callback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/github/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["start"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/github-app/authorize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["github_app_authorize"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/github-app/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["github_app_callback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repositories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_repositories"];
    put?: never;
    post: operations["create_repository"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repositories/{owner}/{name}/pull-requests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_pull_requests"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repositories/{owner}/{name}/pull-requests/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sync_pull_requests"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_settings"];
    put: operations["put_settings"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateRepositoryRequest: {
      repository: string;
    };
    CreateRepositoryResponse: {
      repository: components["schemas"]["RepositoryDto"];
    };
    HealthResponse: {
      database: components["schemas"]["HealthStatus"];
      status: components["schemas"]["HealthStatus"];
    };
    /** @enum {string} */
    HealthStatus: "ok";
    ListPullRequestsResponse: {
      pullRequests: components["schemas"]["PullRequestDto"][];
    };
    ListRepositoriesResponse: {
      repositories: components["schemas"]["RepositoryDto"][];
    };
    MeResponse: {
      user?: null | components["schemas"]["UserDto"];
    };
    PullRequestDto: {
      authorLogin?: string | null;
      closedAt?: string | null;
      createdAt: string;
      draft: boolean;
      /** Format: int64 */
      githubId: number;
      htmlUrl: string;
      mergedAt?: string | null;
      /** Format: int64 */
      number: number;
      state: string;
      syncedAt: string;
      title: string;
      updatedAt: string;
    };
    /** @enum {string} */
    PullRequestErrorCode:
      | "authorization_required"
      | "invalid_repository"
      | "repository_not_tracked"
      | "sync_failed";
    PullRequestErrorResponse: {
      error: components["schemas"]["PullRequestErrorCode"];
    };
    RepositoryDto: {
      createdAt: string;
      fullName: string;
      htmlUrl: string;
      name: string;
      owner: string;
    };
    /** @enum {string} */
    RepositoryErrorCode: "duplicate_repository" | "invalid_repository" | "repository_save_failed";
    RepositoryErrorResponse: {
      error: components["schemas"]["RepositoryErrorCode"];
    };
    SettingsResponse: {
      theme: components["schemas"]["Theme"];
    };
    SyncPullRequestsResponse: {
      complete: boolean;
      /** Format: int64 */
      nextPage?: number | null;
      pullRequests: components["schemas"]["PullRequestDto"][];
      syncedCount: number;
    };
    /** @enum {string} */
    Theme: "dark" | "light" | "system";
    UpdateSettingsRequest: {
      theme: components["schemas"]["Theme"];
    };
    UserDto: {
      avatarUrl?: string | null;
      displayName: string;
      id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  callback: {
    parameters: {
      query?: {
        code?: string | null;
        state?: string | null;
        error?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Creates a local session and redirects to the frontend */
      303: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description GitHub OAuth is not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  start: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirects to GitHub OAuth */
      303: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description GitHub OAuth is not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session cleared */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current authenticated user, if any */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
    };
  };
  github_app_authorize: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirects to GitHub App installation flow */
      303: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description GitHub App is not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  github_app_callback: {
    parameters: {
      query?: {
        installation_id?: number | null;
        setup_action?: string | null;
        state?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Stores GitHub App installation and redirects to frontend */
      303: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Backend health check */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  list_repositories: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user's tracked repositories */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListRepositoriesResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_repository: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRepositoryRequest"];
      };
    };
    responses: {
      /** @description Tracked repository created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateRepositoryResponse"];
        };
      };
      /** @description Invalid GitHub repository */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepositoryErrorResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepositoryErrorResponse"];
        };
      };
      /** @description Repository is already tracked */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepositoryErrorResponse"];
        };
      };
    };
  };
  list_pull_requests: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Stored pull requests for a tracked repository */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListPullRequestsResponse"];
        };
      };
      /** @description Invalid repository */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Repository is not tracked */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
    };
  };
  sync_pull_requests: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description One page of pull requests synced */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SyncPullRequestsResponse"];
        };
      };
      /** @description Invalid repository */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description GitHub App authorization required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
      /** @description Repository is not tracked */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PullRequestErrorResponse"];
        };
      };
    };
  };
  get_settings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user settings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  put_settings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateSettingsRequest"];
      };
    };
    responses: {
      /** @description Updated user settings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
